export const FETCH_LICENSES_START = 'SET_GIT_LICENSES';
export const FETCH_LICENSES_SUCCESS = 'FETCH_LICENSES_SUCCESS';
export const FETCH_LICENSES_ERROR = 'FETCH_LICENSES_ERROR';

export const FETCH_REPOSITORIES_START = 'FETCH_REPOSITORIES_START';
export const FETCH_REPOSITORIES_ERROR = 'FETCH_REPOSITORIES_ERROR';
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';